/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/sign_up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Redirects to the Auth0.js authorization page to register a new user or log in as an existing user. */
        get: operations["signUp"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sign_up/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Completes the user registration with an authorize token. If the user is already registered, this behaves as logging in. This endpoint is registered as the callback on Auth0.js. */
        post: operations["signUpCallback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Gets the new access token with a refresh token. */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Updates the user information. */
        post: operations["updateUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserInfo: {
            /**
             * @description The identifier of user.
             * @example 969186e5-3e25-4fb0-b42a-a82183025b60
             */
            id?: string;
            /**
             * @description The display name of user.
             * @example Mikuroさいな
             */
            name?: string;
            /**
             * Format: date-time
             * @description The registered date of user.
             * @example 2022-12-31T23:59:59.999Z
             */
            created_at?: string;
            /**
             * @description The user is frozen about submitting the new scores.
             * @default false
             */
            is_frozen: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signUp: {
        parameters: {
            query: {
                /** @description The state string kept during the sign up scheme for preventing from CSRF attacks. It should be specified bytes generated from the cryptographic random generator. */
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirected to the external page with some query parameters. */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The parameter state not specified. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unexpected errors. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    signUpCallback: {
        parameters: {
            query: {
                /** @description OAuth 2.0 authorization code. */
                code: string;
                /** @description The state string that you passed to `/sign_up`. You MUST check whether the state is kept for preventing the scheme from CSRF attacks. */
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user registration succeed. And returns the tokens available on other APIs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Your identifier. */
                        user_id?: string;
                        /** @description A Bearer token which you can use on other APIs of this service to authorize. */
                        access_token?: string;
                        /** @description A Bearer token which you can pass to `/refresh` when the access token has expired. */
                        refresh_token?: string;
                    };
                };
            };
            /** @description Bad parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The authorization code is expired. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description The refresh token returned from `/sign_up/callback`. */
                    refresh_token?: string;
                    required?: unknown;
                };
            };
        };
        responses: {
            /** @description Succeed to regenerate a new access token. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description A new access token. */
                        access_token?: string;
                        /** @description A new refresh token. */
                        refresh_token?: string;
                    };
                };
            };
            /** @description Bad parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The refresh token is not provided. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The refresh token is expired. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    name?: string;
                };
            };
        };
        responses: {
            /** @description Succeed to update your user information. And returns the current information. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserInfo"];
                };
            };
            /** @description Bad parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user of the specified id not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
