/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lists all registered users. */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Checks the user information and its play history for investigation. */
        get: operations["inspectUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/freeze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Freezes the user. It disallows the user submitting the new scores until the moderator unfreezes it. */
        post: operations["freezeUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/unfreeze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unfreezes the user. It allows the user submitting the new scores. */
        post: operations["unfreezeUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserInfo: {
            /**
             * @description The identifier of user.
             * @example 969186e5-3e25-4fb0-b42a-a82183025b60
             */
            id: string;
            /**
             * @description The display name of user.
             * @example Mikuroさいな
             */
            name?: string;
            /**
             * Format: date-time
             * @description The registered date of user.
             * @example 2022-12-31T23:59:59.999Z
             */
            created_at: string;
            /**
             * @description The user is frozen about submitting the new scores.
             * @default false
             */
            is_frozen: boolean;
        };
        /**
         * @example {
         *       "meticulous": 2,
         *       "precise": 1,
         *       "good": 5,
         *       "offbeat": 9,
         *       "missed": 3
         *     }
         */
        ScoreCount: {
            /**
             * Format: int64
             * @description Count of the notes hit the grade A.
             */
            meticulous: number;
            /**
             * Format: int64
             * @description Count of the notes hit the grade B.
             */
            precise: number;
            /**
             * Format: int64
             * @description Count of the notes hit the grade C.
             */
            good: number;
            /**
             * Format: int64
             * @description Count of the notes hit the grade D.
             */
            offbeat: number;
            /**
             * Format: int64
             * @description Count of the notes didn't hit.
             */
            missed: number;
        };
        ScoreboardEntry: {
            /**
             * @description The identifier of this record.
             * @example preexisting0
             */
            id: string;
            /**
             * Format: int64
             * @description The achieved score.
             * @example 543210
             */
            score: number;
            /**
             * Format: int64
             * @description Count of notes the player can hit.
             * @example 20
             */
            total: number;
            /**
             * Format: int64
             * @description Count of notes the player hit consecutively.
             * @example 1
             */
            combo: number;
            count: components["schemas"]["ScoreCount"];
            /**
             * Format: int64
             * @description Index of the plays by the player.
             * @example 1
             */
            play_number: number;
            /**
             * Format: int64
             * @description Count of the plays by the player.
             * @example 2
             */
            play_count: number;
            /**
             * Format: date-time
             * @description The submission time of the record.
             * @example 2022-12-31T23:59:59.999Z
             */
            recorded_at: string;
            player: {
                /**
                 * @description The player name.
                 * @example tester2
                 */
                name?: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listUsers: {
        parameters: {
            query?: {
                /** @description Filters the users registered since. */
                since?: string;
                /** @description Filters the users registered until. */
                until?: string;
                /** @description Filters the users who the name matching to. */
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns the users matching conditions built from query parameters. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        users?: components["schemas"]["UserInfo"][];
                    };
                };
            };
            /** @description Bad parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Expected to authorize as a moderator. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    inspectUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns the user information and its play history. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        info?: components["schemas"]["UserInfo"];
                        plays?: components["schemas"]["ScoreboardEntry"][];
                    };
                };
            };
            /** @description Expected to authorize as a moderator. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    freezeUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The moderation succeed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Expected to authorize as a moderator. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unfreezeUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The moderation succeed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Expected to authorize as a moderator. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The user not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
