/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/{chart_md5}/{play_mode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves the leaderboard of the score on the play mode. */
        get: operations["getLeaderboard"];
        put?: never;
        /** Submits the high score of the score on the leader board and the play mode. */
        post: operations["submitScore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{chart_md5}/{play_mode}/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves the play stats detail of the user. */
        get: operations["getScore"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        PlayMode: "KB" | "BM" | "TS";
        /**
         * @example {
         *       "meticulous": 2,
         *       "precise": 1,
         *       "good": 5,
         *       "offbeat": 9,
         *       "missed": 3
         *     }
         */
        ScoreCount: {
            /**
             * Format: int64
             * @description Count of the notes hit the grade A.
             */
            meticulous: number;
            /**
             * Format: int64
             * @description Count of the notes hit the grade B.
             */
            precise: number;
            /**
             * Format: int64
             * @description Count of the notes hit the grade C.
             */
            good: number;
            /**
             * Format: int64
             * @description Count of the notes hit the grade D.
             */
            offbeat: number;
            /**
             * Format: int64
             * @description Count of the notes didn't hit.
             */
            missed: number;
        };
        Score: {
            /**
             * Format: int64
             * @description The achieved score.
             * @example 123456
             */
            score: number;
            /**
             * Format: int64
             * @description Count of notes the player hit consecutively.
             * @example 46
             */
            combo: number;
            count: components["schemas"]["ScoreCount"];
            /**
             * Format: int64
             * @description Count of notes the player can hit.
             * @example 20
             */
            total: number;
            /**
             * @description The judgement transition log of the play. It consists of A, B, C, D and M.
             * @example AMCDCB
             */
            log?: string;
        };
        ScoreboardEntry: {
            /**
             * @description The identifier of this record.
             * @example preexisting0
             */
            id: string;
            /**
             * Format: int64
             * @description The achieved score.
             * @example 543210
             */
            score: number;
            /**
             * Format: int64
             * @description Count of notes the player can hit.
             * @example 20
             */
            total: number;
            /**
             * Format: int64
             * @description Count of notes the player hit consecutively.
             * @example 1
             */
            combo: number;
            count: components["schemas"]["ScoreCount"];
            /**
             * Format: int64
             * @description Index of the plays by the player.
             * @example 1
             */
            play_number: number;
            /**
             * Format: int64
             * @description Count of the plays by the player.
             * @example 2
             */
            play_count: number;
            /**
             * Format: date-time
             * @description The submission time of the record.
             * @example 2022-12-31T23:59:59.999Z
             */
            recorded_at: string;
            player: {
                /**
                 * @description The player name.
                 * @example tester2
                 */
                name?: string;
            };
        };
        ScoreboardRow: {
            /**
             * Format: int32
             * @description The current rank in the leaderboard.
             * @example 1
             */
            rank?: number;
            entry: components["schemas"]["ScoreboardEntry"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLeaderboard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chart_md5: string;
                play_mode: components["schemas"]["PlayMode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Query result of the leaderboard, sorted by its score in descend order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreboardRow"][];
                };
            };
            /** @description Bad path parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    submitScore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chart_md5: string;
                play_mode: components["schemas"]["PlayMode"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Score"];
            };
        };
        responses: {
            /** @description Submits the score by the authenticated user. Then returns the inserted your entry in the leaderboard. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreboardRow"];
                };
            };
            /** @description Bad parameters. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No authorization provided. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getScore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chart_md5: string;
                play_mode: components["schemas"]["PlayMode"];
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Query result of the high score. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreboardRow"];
                };
            };
            /** @description Such record of the chart by the user not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
