openapi: 3.1.0

info:
  title: Scoreboard API
  version: 1.0.0
  license:
    name: Apache 2.0
    identifier: Apache-2.0

servers:
  - url: https://bemuse-scoreboard.mikuroxina.workers.dev/api/scoreboard
    description: Production env
  - url: https://staging.bemuse-scoreboard.mikuroxina.workers.dev/api/scoreboard
    description: Staging env

components:
  securitySchemes:
    TokenAuth:
      type: http
      scheme: bearer
  schemas:
    PlayMode:
      type: string
      enum:
        - KB
        - BM
        - TS
    ScoreCount:
      required:
        - meticulous
        - precise
        - good
        - offbeat
        - missed
      properties:
        meticulous:
          type: integer
          format: int64
          description: Count of the notes hit the grade A.
        precise:
          type: integer
          format: int64
          description: Count of the notes hit the grade B.
        good:
          type: integer
          format: int64
          description: Count of the notes hit the grade C.
        offbeat:
          type: integer
          format: int64
          description: Count of the notes hit the grade D.
        missed:
          type: integer
          format: int64
          description: Count of the notes didn't hit.
      examples:
        - meticulous: 2
          precise: 1
          good: 5
          offbeat: 9
          missed: 3
    Score:
      required:
        - score
        - combo
        - count
        - total
      properties:
        score:
          type: integer
          format: int64
          description: The achieved score.
          examples:
            - 123456
        combo:
          type: integer
          format: int64
          description: Count of notes the player hit consecutively.
          examples:
            - 46
        count:
          $ref: '#/components/schemas/ScoreCount'
        total:
          type: integer
          format: int64
          description: Count of notes the player can hit.
          examples:
            - 20
        log:
          type: string
          description:
            The judgement transition log of the play. It consists of A, B, C, D
            and M.
          examples:
            - AMCDCB
    ScoreboardEntry:
      required:
        - id
        - score
        - total
        - combo
        - count
        - play_number
        - play_count
        - recorded_at
        - player
      properties:
        id:
          type: string
          description: The identifier of this record.
          examples:
            - preexisting0
        score:
          type: number
          format: int64
          description: The achieved score.
          examples:
            - 543210
        total:
          type: number
          format: int64
          description: Count of notes the player can hit.
          examples:
            - 20
        combo:
          type: number
          format: int64
          description: Count of notes the player hit consecutively.
          examples:
            - 1
        count:
          $ref: '#/components/schemas/ScoreCount'
        play_number:
          type: number
          format: int64
          description: Index of the plays by the player.
          examples:
            - 1
        play_count:
          type: number
          format: int64
          description: Count of the plays by the player.
          examples:
            - 2
        recorded_at:
          type: string
          format: date-time
          description: The submission time of the record.
          examples:
            - 2022-12-31T23:59:59.999Z
        player:
          type: object
          properties:
            name:
              type: string
              description: The player name.
              examples:
                - tester2
    ScoreboardRow:
      required:
        - entry
      properties:
        rank:
          type: integer
          format: int32
          description: The current rank in the leaderboard.
          examples:
            - 1
        entry:
          $ref: '#/components/schemas/ScoreboardEntry'

paths:
  /{chart_md5}/{play_mode}:
    get:
      summary: 'Retrieves the leaderboard of the score on the play mode.'
      operationId: getLeaderboard
      security: []
      parameters:
        - name: chart_md5
          in: path
          schema:
            type: string
          required: true
        - name: play_mode
          in: path
          schema:
            $ref: '#/components/schemas/PlayMode'
          required: true
      responses:
        '200':
          description:
            Query result of the leaderboard, sorted by its score in descend
            order.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ScoreboardRow'
        '400':
          description: Bad path parameters.
    post:
      summary:
        'Submits the high score of the score on the leader board and the play
        mode.'
      operationId: submitScore
      security:
        - TokenAuth: []
      parameters:
        - name: chart_md5
          in: path
          schema:
            type: string
          required: true
        - name: play_mode
          in: path
          schema:
            $ref: '#/components/schemas/PlayMode'
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Score'
      responses:
        '200':
          description:
            Submits the score by the authenticated user. Then returns the
            inserted your entry in the leaderboard.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScoreboardRow'
        '400':
          description: Bad parameters.
        '401':
          description: No authorization provided.
  /{chart_md5}/{play_mode}/{user_id}:
    get:
      summary: Retrieves the play stats detail of the user.
      operationId: getScore
      security: []
      parameters:
        - name: chart_md5
          in: path
          schema:
            type: string
          required: true
        - name: play_mode
          in: path
          schema:
            $ref: '#/components/schemas/PlayMode'
          required: true
        - name: user_id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Query result of the high score.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScoreboardRow'
        '404':
          description: Such record of the chart by the user not found.
