packages:
  - bemuse
  - website
  - e2e
  - build-scripts
  - packages/**

ignoredBuiltDependencies:
  - '@fortawesome/fontawesome-common-types'
  - '@fortawesome/fontawesome-svg-core'
  - '@fortawesome/free-brands-svg-icons'
  - '@fortawesome/free-regular-svg-icons'
  - '@fortawesome/free-solid-svg-icons'
  - '@parcel/watcher'
  - core-js
  - es5-ext
  - fsevents

onlyBuiltDependencies:
  - esbuild
  - puppeteer
