name = "bemuse-scoreboard"
compatibility_date = "2026-03-10"
main = "src/main.ts"

[vars]
AUTH0_AUDIENCE = "https://bemuse-scoreboard.mikuroxina.workers.dev/"
AUTH0_DOMAIN = "https://mikuroxina.jp.auth0.com/"
AUTH0_CLIENT_ID = "08G3QzJ8z1rh6pElmVzbEl98j7yXI9ab"
