name = "bemuse-scoreboard"
compatibility_date = "2026-03-10"
compatibility_flags = ["nodejs_compat"]
main = "src/main.tsx"
assets = { directory = "./dist" }
upload_source_maps = true

[vars]
VITE_AUTH0_AUDIENCE = "https://mikuroxina.jp.auth0.com/api/v2/"
VITE_AUTH0_DOMAIN = "mikuroxina.jp.auth0.com"
VITE_AUTH0_CLIENT_ID = "08G3QzJ8z1rh6pElmVzbEl98j7yXI9ab"

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[[d1_databases]]
binding = "score"
database_name = "score"
database_id = "43f545a9-cf4c-4e52-9a0f-c81155c2cff0"

[[ratelimits]]
name = "SUBMISSION_RATE_LIMITER"
namespace_id = "1001"
[ratelimits.simple]
limit = 2
period = 60
