name: 'Set up project'
description: 'Sets up Node.js, Rush, and project dependencies.'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: .tool-versions
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
    - name: Setup Rush cache
      uses: ./.github/actions/rush-cache
    - name: Install Deps
      run: pnpm install
      shell: bash
