name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  merge_group:
  workflow_dispatch:

env:
  NODE_FLAGS: --max_old_space_size=4096

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Set up project
        uses: ./.github/actions/setup-project
      - name: Build
        run: pnpm run build
      - name: Compress build output
        if: always()
        run: tar -cvzf dist.tar.gz packages/bemuse/dist
      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: bemuse-build-${{ github.sha }}
          path: dist.tar.gz
      - name: Checks
        run: pnpm run --filter bemuse pre-deploy
      - name: Publish dry run
        run: pnpm publish -r --dry-run --no-git-checks
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up project
        uses: ./.github/actions/setup-project
      - name: Build dependencies
        run: pnpm run build
      - name: Typecheck
        run: pnpm run --filter bemuse typecheck
  tidy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up project
        uses: ./.github/actions/setup-project
      - name: Build
        run: pnpm run build
      - name: Lint all
        run: pnpm run -r lint
        if: always()
      - name: Semgrep
        uses: ./.github/actions/semgrep
        if: always()
  test:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.59.1-noble
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up project
        uses: ./.github/actions/setup-project
      - name: Build
        run: pnpm run build
      - name: Test with coverage
        run: pnpm run -r coverage
      - uses: codecov/codecov-action@v6
        with:
          files: ./packages/bemuse/coverage/clover.xml,./packages/bemuse-indexer/coverage/clover.xml,./packages/bemuse-notechart/coverage/clover.xml,./packages/bemuse-tools/coverage/clover.xml,./packages/bms/coverage/clover.xml,./packages/bmson/coverage/clover.xml,./packages/monetizer/coverage/clover.xml
          use_oidc: true
      - name: Run E2E tests
        run: pnpm run --filter bemuse-e2e test
      - name: Upload test report
        uses: actions/upload-artifact@v7
        if: failure()
        with:
          name: playwright-report
          path: ./packages/e2e/playwright-report
